---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    pod-reloader.deckhouse.io/auto: "true"
spec:
  selector: 
    matchLabels: 
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
        - mountPath: /app/index.html
          name: static
          subPath: index.html
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
      - name: static
        configMap:
          name: static

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
